### ISSUE TITLE
How some protectors convert methods to delegates to confuse reverse engineer ? How we can understand it's algorithm ?

### ISSUE THREAD

**Issue by Mandofskii** [XenocodeRCE/BasicProxyObfucator#1]
![image](https://user-images.githubusercontent.com/59086060/162405628-ea1ab19c-6a92-447b-a05c-aad44b536929.png)
![image](https://user-images.githubusercontent.com/59086060/162405760-a9642b23-bdd5-4975-a729-fc307e24aa6e.png)
Thank you ;)

**Comment by XenocodeRCE** [comment]
The code of this particular protection is here https://github.com/yck1509/ConfuserEx/tree/master/Confuser.Protections/ReferenceProxy

its not for beginners, code is complexe. You can debug the project and try to understand how it works :)
